from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.middleware.trustedhost import TrustedHostMiddleware
from api.agents_router import agents_router
from api.models import HealthCheckResponse
from slowapi import Limiter, _rate_limit_exceeded_handler
from slowapi.util import get_remote_address
from slowapi.errors import RateLimitExceeded
import time
import os


# Create rate limiter
limiter = Limiter(key_func=get_remote_address)

# Create FastAPI application
app = FastAPI(
    title="RAG Agent API",
    description="API for RAG-enabled agent with OpenAI and Qdrant integration",
    version="1.0.0",
    # Add security headers
    root_path=os.getenv("ROOT_PATH", "")
)

# Set up rate limiting
app.state.limiter = limiter
app.add_exception_handler(RateLimitExceeded, _rate_limit_exceeded_handler)

# Add security middleware
app.add_middleware(
    TrustedHostMiddleware,
    allowed_hosts=os.getenv("ALLOWED_HOSTS", "localhost,127.0.0.1").split(",")
)

# Add CORS middleware with specific origins
app.add_middleware(
    CORSMiddleware,
    allow_origins=os.getenv("ALLOWED_ORIGINS", "http://localhost,http://127.0.0.1").split(","),
    allow_credentials=True,
    allow_methods=["GET", "POST"],
    allow_headers=["*"],
)

# Include agent router
app.include_router(agents_router)


@app.get("/")
@limiter.limit("100/minute")  # Limit to 100 requests per minute per IP
def read_root():
    """
    Root endpoint for the API
    """
    return {"message": "RAG Agent API is running"}


@app.get("/health", response_model=HealthCheckResponse)
@limiter.limit("30/minute")  # Limit to 30 health check requests per minute per IP
def health_check():
    """
    Health check endpoint to verify service availability
    """
    return HealthCheckResponse(
        status="healthy",
        timestamp=str(time.time())
    )


@app.get("/docs")
@limiter.limit("50/minute")  # Limit to 50 requests per minute per IP
def api_docs():
    """
    API documentation endpoint (auto-generated by FastAPI)
    """
    return {"message": "API documentation available at /docs"}


# This allows the application to be run with uvicorn
if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="0.0.0.0", port=8000)